# Generated by Django 5.1.5 on 2025-08-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('is_used', models.BooleanField(default=False, verbose_name='Використано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Використано о')),
                ('expires_at', models.DateTimeField(verbose_name='Діє до')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.customer', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Код знижки',
                'verbose_name_plural': 'Коди знижок',
                'ordering': ['-created_at'],
            },
        ),
    ]
